var ANNEXES = {
  b1: [
    { n: 1,
      titre: "Histoire et identité de Bellewaerde",
      pages: "10-11",
      contenu: "Origines du parc (1954, parc animalier et floral), évolution vers les attractions à sensations dans les années 1970-1990, intégration à la Compagnie des Alpes en 2013, ouverture de l'Aquapark en 2019, et attractions phares actuelles.",
      utile: "Donne les éléments d'identité et d'histoire de marque à mobiliser dans le positionnement et les différenciateurs." },
    { n: 2,
      titre: "L'histoire de la mascotte Léo",
      pages: "12",
      contenu: "Récit fictif du lion Léo, mascotte du parc incarnant convivialité, nature et respect, et justification narrative du nom de l'hôtel « Le Royaume de Léo ».",
      utile: "Sert de fil rouge pour l'univers thématique de l'hôtel et pour l'argumentaire de marque dans la vidéo de présentation." },
    { n: 3,
      titre: "Cahier des charges du projet hôtelier",
      pages: "13-16",
      contenu: "Contexte et objectifs du projet, répartition des 100 chambres, espaces communs et services, contraintes techniques et architecturales, engagements RSE, budget (18-21 M€) et planning jusqu'à l'ouverture en N+3.",
      utile: "Fournit les contraintes chiffrées non négociables à respecter dans toute proposition — budget, capacité, délais, RSE." },
    { n: 4,
      titre: "Maquettes de l'hôtel",
      pages: "17-19",
      contenu: "Vues extérieures de la façade, hall d'accueil thématisé, chambre classique et chambre VIP.",
      utile: "Donne des repères visuels concrets pour décrire l'expérience et les différenciateurs perçus par le client." },
    { n: 5,
      titre: "Emplacement de l'hôtel dans le parc",
      pages: "20-21",
      contenu: "Position de l'hôtel entre les zones India, Kids Park et Jungle, accès depuis les entrées Lion et Mexico, et cartographie générale du parc.",
      utile: "Utile pour situer l'intégration de l'hôtel dans le parcours visiteur et pour l'accessibilité PMR." },
    { n: 6,
      titre: "Étude de marché des parcs d'attraction",
      pages: "22-24",
      contenu: "Contexte touristique belge, tendances des visiteurs (séjours courts, essor de l'hébergement), saisonnalité de la fréquentation, et profils chiffrés de quatre parcs concurrents.",
      utile: "Fournit les données de marché et de concurrence à citer dans la veille, le diagnostic et le positionnement." }
  ],
  b2: [
    { n: 1,
      titre: "Présentation complète de Bambu Lab",
      pages: "12-13",
      contenu: "Fondation en 2020 par des ingénieurs issus de DJI, positionnement (rendre la haute technologie accessible), management agile orienté R&D, et stratégie (logiciel Bambu Farm Manager en LAN sans cloud, ambition de croissance, éco-système matériaux/logiciels/support).",
      utile: "Donne les éléments d'identité, de culture et de positionnement de l'entreprise à mobiliser dans le ciblage, les actions marketing et le ton des supports de communication." },
    { n: 2,
      titre: "Description du produit « H2S »",
      pages: "14-15",
      contenu: "Caractéristiques techniques (volume d'impression, température, chambre chauffée, 23 capteurs, 3 caméras, sécurité, connectivité) et avantages pédagogiques/professionnels pour les écoles d'ingénieurs, de design et les bureaux d'études.",
      utile: "Fournit l'argumentaire produit à reprendre dans le message publicitaire et les supports de communication." },
    { n: 3,
      titre: "Le marché de l'impression 3D en 2025",
      pages: "15-16",
      contenu: "Structure du marché (fabricants, éditeurs de logiciels CAO, prestataires de services), acteurs de référence (Stratasys, 3D Systems, Prodways...), taille et croissance (171 Md$ en 2020, 703 Md$ visés en 2030, +22 %/an), limites et réglementation (marquage CE, France Additive).",
      utile: "Fournit les données de marché à citer pour justifier les actions marketing, en cohérence avec la compétence C2.1." },
    { n: 4,
      titre: "Données clés et analyse de la renommée des écoles privées parisiennes",
      pages: "16-17",
      contenu: "L'Île-de-France concentre 40 % des grandes écoles et 120 000 étudiants par an, 20 à 30 % d'étudiants étrangers selon les cursus, plus de 80 % d'insertion professionnelle en moins de 6 mois, et un réseau d'alumni influent.",
      utile: "Fournit les données de ciblage et d'audience pour le plan de prospection, les personas et le message publicitaire." },
    { n: 5,
      titre: "Test et avis sur la Bambu Lab H2S par Tom's Basement",
      pages: "18",
      contenu: "Retour d'expérience vidéo d'une chaîne spécialisée en impression 3D sur les performances et la fiabilité de la H2S.",
      utile: "Sert de preuve sociale et de source crédible à mobiliser dans les contenus et supports de communication." },
    { n: 6,
      titre: "Briefing sur les ressources mises à disposition du futur partenaire-distributeur",
      pages: "18-19",
      contenu: "Phase pilote de 6 mois en Île-de-France : deux référents internes Bambu Lab, pack de démonstration (imprimantes, brochures, médiathèque digitale, consommables), budget pilote de 20 000 € et remise commerciale de 20 % sur les imprimantes de démonstration.",
      utile: "Fournit les contraintes chiffrées non négociables — budget, ressources humaines et matérielles — pour le cahier des charges, le budget des actions et la négociation avec le prestataire." }
  ],
  b4: [
    { n: 1,
      titre: "Brief sur le projet « For The First Time – Masterclass »",
      pages: "9-11",
      contenu: "Contexte, objectifs du projet, brief créatif (ton, identité graphique, narration, supports), livrables attendus et indicateurs de réussite chiffrés (plus de 500 000 vues, plus de 8 % d'engagement, plus de 20 retombées presse, plus de 100 invités, 100 % des jalons tenus).",
      utile: "Fournit le cadre de référence complet — objectifs, exigences créatives et indicateurs — pour évaluer la demande, formuler les objectifs SMART et juger la conformité des livrables." },
    { n: 2,
      titre: "Présentation de « Drumeo »",
      pages: "11-12",
      contenu: "Entreprise canadienne d'e-learning musical fondée en 2011, plus de 50 000 membres actifs, plus de 5 millions d'abonnés YouTube, format phare « For The First Time », chiffre d'affaires du groupe Musora supérieur à 16 M$.",
      utile: "Donne le contexte, la taille et la culture de marque de l'annonceur, utile pour cerner ses enjeux et exigences vis-à-vis du prestataire." },
    { n: 3,
      titre: "Présentation de « Your Story Agency »",
      pages: "12-13",
      contenu: "Agence de production audiovisuelle canadienne basée à Vancouver, collaborations avec des marques internationales (Marvel, Disney, Hublot...), équipe pluridisciplinaire (réalisateurs, directeurs artistiques, monteurs, graphistes, pilotes de drones).",
      utile: "Permet d'évaluer les facteurs internes de YSA (compétences, organisation) face à ce projet inédit de captation musicale live." },
    { n: 4,
      titre: "Les équipes missionnées sur le projet",
      pages: "13-18",
      contenu: "Fiches des six intervenants et leurs responsabilités sur le projet : côté Drumeo, Jared Falk (PDG), Brandon Toews (animateur/créateur de contenu) et Dave Atkinson (responsable marketing/communication) ; côté YSA, Braeden Fairbridge (PDG), Colin Marshall (directeur créatif) et Chris Mike (responsable vidéaste/photographie).",
      utile: "Détaille le rôle exact de chaque membre des trois binômes, nécessaire pour analyser leurs attentes réciproques." },
    { n: 5,
      titre: "Contrat de collaboration entre Drumeo et Your Story Agency",
      pages: "18-20",
      contenu: "Missions des deux parties, phases de contrôle et d'évaluation, moyens de communication privilégiés (réunions bimensuelles en visioconférence, rapports mensuels, tableau de bord partagé, canal instantané), durée du contrat (4 mois) et planification générale (préparation 1 à 2 mois, jour J, post-production 1 à 2 mois).",
      utile: "Fournit le cadre contractuel et le calendrier à respecter pour l'organisation du travail et le rétroplanning." },
    { n: 6,
      titre: "Échange sur l'avancée du projet et l'annonce de la formation",
      pages: "20-22",
      contenu: "Dialogue entre Jared Falk (Drumeo) et Braeden Fairbridge (YSA) détaillant les outils utilisés au quotidien : Trello pour les jalons, ClickUp pour la validation des tâches et de la formation, Google Drive pour les documents, suite Adobe pour la création.",
      utile: "Donne la liste réelle des outils collaboratifs déjà en place, à mobiliser pour les questions sur l'organisation du travail et les routines d'équipe." },
    { n: 7,
      titre: "Mise en place d'une formation en captation musicale live",
      pages: "22-24",
      contenu: "Programme détaillé de la formation déjà existante : 5 modules (univers Drumeo, captation multi-caméras, prise de son, post-production, atelier pratique), sur 4 jours soit 28 heures.",
      utile: "Sert de référence pour ne pas proposer une formation qui fait doublon, et de modèle de structure pour concevoir une nouvelle session." },
    { n: 8,
      titre: "Plan de la salle de concert et descriptif technique",
      pages: "25-27",
      contenu: "Vancouver Civic Theatres : salle circulaire de 400 à 600 places, scène centrale, accessibilité (2 zones PMR, signalétique bilingue, boucles magnétiques, zones calmes), sécurité et zones fonctionnelles (régie, presse/VIP, backstage), équipements son/vidéo/éclairage.",
      utile: "Fournit les données techniques et d'accessibilité nécessaires pour analyser la configuration en O et proposer des améliorations d'inclusion." },
    { n: 9,
      titre: "Premières maquettes faites par l'agence Your Story Agency",
      pages: "27-31",
      contenu: "Aperçus des livrables produits par YSA : publications Facebook, TikTok et Instagram, captations photo des préparatifs et du show, et vignette de la vidéo YouTube finale.",
      utile: "Donne les livrables concrets à comparer au brief créatif pour identifier les écarts et les corrections à demander." }
  ],
  b3: [
    { n: 1,
      titre: "Extrait de la base de données du CRM de l'entreprise",
      pages: "9",
      contenu: "Quatre segments clients chiffrés : jeunes actifs urbains (38 %, 55 % de fidélité), sportifs (25 %, segment le plus fidèle à 68 %), clients « bien-être » (30 %), nouveaux clients de moins de 3 mois (7 %, forte perte après la 1ère commande) — avec fréquence d'achat, panier moyen et observations pour chacun.",
      utile: "Fournit la segmentation chiffrée à mobiliser pour le diagnostic du parcours client et pour cibler le recrutement du panel de l'enquête." },
    { n: 2,
      titre: "Statistiques Google Analytics",
      pages: "10-11",
      contenu: "Données de trafic et de comportement sur le site et l'application PrepMyMeal.",
      utile: "Source quantitative sur le parcours digital, à croiser avec le CRM et les heatmaps pour le diagnostic de l'expérience client." },
    { n: 3,
      titre: "Carte de chaleur de la page d'accueil (partie 1)",
      pages: "12",
      contenu: "Zones de clics et d'attention des visiteurs sur la première partie de la page d'accueil.",
      utile: "Permet d'identifier les zones qui captent réellement l'attention, à confronter aux intentions d'achat." },
    { n: 4,
      titre: "Carte de chaleur de la page d'accueil (partie 2)",
      pages: "13",
      contenu: "Zones de clics et d'attention des visiteurs sur la seconde partie de la page d'accueil.",
      utile: "Complète l'annexe 3 pour une lecture complète du comportement des visiteurs sur la page d'accueil." },
    { n: 5,
      titre: "Commentaires clients à propos de l'entreprise sur Trustpilot.com",
      pages: "14",
      contenu: "Avis clients publiés en ligne sur PrepMyMeal, positifs et négatifs.",
      utile: "Constitue la base de sondés spontanée à évaluer pour la représentativité du panel, et une source de motivations/freins pour le questionnaire de satisfaction." },
    { n: 6,
      titre: "Présentation du projet foodtruck éphémère",
      pages: "15-18",
      contenu: "Description du véhicule et de son organisation, double vocation commerciale et expérientielle, objectifs stratégiques (notoriété, expérience immersive, test de recettes, acquisition, proximité), outils et supports mobilisés (CRM, flyers QR code, caisse, site/app, réseaux sociaux, emailing/SMS, tablettes, heatmaps, social listening), et itinéraire des 8 villes de la tournée.",
      utile: "Fournit le contexte complet du dispositif foodtruck — objectifs, outils et parcours — nécessaire pour cartographier le parcours client et concevoir la section du questionnaire dédiée à la nouveauté." },
    { n: 7,
      titre: "Résultats de la tournée du foodtruck",
      pages: "19-20",
      contenu: "Deux rapports chiffrés par ville (Paris, Lille, Strasbourg, Lyon, Marseille, Toulouse, Bordeaux, Nantes) : nombre de clients, taux de conversion, ventes, inscriptions, satisfaction, retombées digitales, temps d'attente, plat le plus vendu, taux de réachat, engagement digital, coût opérationnel et marge nette.",
      utile: "Données brutes à exploiter pour choisir les KPI, construire le tableau de bord et comparer les résultats aux objectifs du CEO." },
    { n: 8,
      titre: "Brief du CEO avant le lancement de la tournée du foodtruck",
      pages: "21-22",
      contenu: "Objectifs chiffrés fixés par le CEO : 1 200 visiteurs par ville, au moins 35 % de conversion, plus de 100 000 € de CA sur l'ensemble de la tournée, 25 % de taux de réachat, 700 inscriptions par ville, moins de 6 minutes d'attente, note de satisfaction d'au moins 4,3/5, 500 mentions digitales par ville et un taux d'engagement supérieur à 40 %.",
      utile: "Fixe les objectifs de référence indispensables pour choisir des KPI pertinents et mesurer les écarts avec les résultats réels." }
  ]
};
