var ANNEXES = {
  b1: [
    { n: 1,
      titre: "Histoire et identité de Bellewaerde",
      pages: "10-11",
      contenu: "Origines du parc (1954, parc animalier et floral), évolution vers les attractions à sensations dans les années 1970-1990, intégration à la Compagnie des Alpes en 2013, ouverture de l'Aquapark en 2019, et attractions phares actuelles.",
      utile: "Donne les éléments d'identité et d'histoire de marque à mobiliser dans le positionnement et les différenciateurs." },
    { n: 2,
      titre: "L'histoire de la mascotte Léo",
      pages: "12",
      contenu: "Récit fictif du lion Léo, mascotte du parc incarnant convivialité, nature et respect, et justification narrative du nom de l'hôtel « Le Royaume de Léo ».",
      utile: "Sert de fil rouge pour l'univers thématique de l'hôtel et pour l'argumentaire de marque dans la vidéo de présentation." },
    { n: 3,
      titre: "Cahier des charges du projet hôtelier",
      pages: "13-16",
      contenu: "Contexte et objectifs du projet, répartition des 100 chambres, espaces communs et services, contraintes techniques et architecturales, engagements RSE, budget (18-21 M€) et planning jusqu'à l'ouverture en N+3.",
      utile: "Fournit les contraintes chiffrées non négociables à respecter dans toute proposition — budget, capacité, délais, RSE." },
    { n: 4,
      titre: "Maquettes de l'hôtel",
      pages: "17-19",
      contenu: "Vues extérieures de la façade, hall d'accueil thématisé, chambre classique et chambre VIP.",
      utile: "Donne des repères visuels concrets pour décrire l'expérience et les différenciateurs perçus par le client." },
    { n: 5,
      titre: "Emplacement de l'hôtel dans le parc",
      pages: "20-21",
      contenu: "Position de l'hôtel entre les zones India, Kids Park et Jungle, accès depuis les entrées Lion et Mexico, et cartographie générale du parc.",
      utile: "Utile pour situer l'intégration de l'hôtel dans le parcours visiteur et pour l'accessibilité PMR." },
    { n: 6,
      titre: "Étude de marché des parcs d'attraction",
      pages: "22-24",
      contenu: "Contexte touristique belge, tendances des visiteurs (séjours courts, essor de l'hébergement), saisonnalité de la fréquentation, et profils chiffrés de quatre parcs concurrents.",
      utile: "Fournit les données de marché et de concurrence à citer dans la veille, le diagnostic et le positionnement." }
  ],
  b2: [
    { n: 1,
      titre: "Présentation complète de Bambu Lab",
      pages: "12-13",
      contenu: "Fondation en 2020 par des ingénieurs issus de DJI, positionnement (rendre la haute technologie accessible), management agile orienté R&D, et stratégie (logiciel Bambu Farm Manager en LAN sans cloud, ambition de croissance, éco-système matériaux/logiciels/support).",
      utile: "Donne les éléments d'identité, de culture et de positionnement de l'entreprise à mobiliser dans le ciblage, les actions marketing et le ton des supports de communication." },
    { n: 2,
      titre: "Description du produit « H2S »",
      pages: "14-15",
      contenu: "Caractéristiques techniques (volume d'impression, température, chambre chauffée, 23 capteurs, 3 caméras, sécurité, connectivité) et avantages pédagogiques/professionnels pour les écoles d'ingénieurs, de design et les bureaux d'études.",
      utile: "Fournit l'argumentaire produit à reprendre dans le message publicitaire et les supports de communication." },
    { n: 3,
      titre: "Le marché de l'impression 3D en 2025",
      pages: "15-16",
      contenu: "Structure du marché (fabricants, éditeurs de logiciels CAO, prestataires de services), acteurs de référence (Stratasys, 3D Systems, Prodways...), taille et croissance (171 Md$ en 2020, 703 Md$ visés en 2030, +22 %/an), limites et réglementation (marquage CE, France Additive).",
      utile: "Fournit les données de marché à citer pour justifier les actions marketing, en cohérence avec la compétence C2.1." },
    { n: 4,
      titre: "Données clés et analyse de la renommée des écoles privées parisiennes",
      pages: "16-17",
      contenu: "L'Île-de-France concentre 40 % des grandes écoles et 120 000 étudiants par an, 20 à 30 % d'étudiants étrangers selon les cursus, plus de 80 % d'insertion professionnelle en moins de 6 mois, et un réseau d'alumni influent.",
      utile: "Fournit les données de ciblage et d'audience pour le plan de prospection, les personas et le message publicitaire." },
    { n: 5,
      titre: "Test et avis sur la Bambu Lab H2S par Tom's Basement",
      pages: "18",
      contenu: "Retour d'expérience vidéo d'une chaîne spécialisée en impression 3D sur les performances et la fiabilité de la H2S.",
      utile: "Sert de preuve sociale et de source crédible à mobiliser dans les contenus et supports de communication." },
    { n: 6,
      titre: "Briefing sur les ressources mises à disposition du futur partenaire-distributeur",
      pages: "18-19",
      contenu: "Phase pilote de 6 mois en Île-de-France : deux référents internes Bambu Lab, pack de démonstration (imprimantes, brochures, médiathèque digitale, consommables), budget pilote de 20 000 € et remise commerciale de 20 % sur les imprimantes de démonstration.",
      utile: "Fournit les contraintes chiffrées non négociables — budget, ressources humaines et matérielles — pour le cahier des charges, le budget des actions et la négociation avec le prestataire." }
  ]
};
