var ANNEXES = {
  b1: [
    { n: 1,
      titre: "Histoire et identité de Bellewaerde",
      pages: "10-11",
      contenu: "Origines du parc (1954, parc animalier et floral), évolution vers les attractions à sensations dans les années 1970-1990, intégration à la Compagnie des Alpes en 2013, ouverture de l'Aquapark en 2019, et attractions phares actuelles.",
      utile: "Donne les éléments d'identité et d'histoire de marque à mobiliser dans le positionnement et les différenciateurs." },
    { n: 2,
      titre: "L'histoire de la mascotte Léo",
      pages: "12",
      contenu: "Récit fictif du lion Léo, mascotte du parc incarnant convivialité, nature et respect, et justification narrative du nom de l'hôtel « Le Royaume de Léo ».",
      utile: "Sert de fil rouge pour l'univers thématique de l'hôtel et pour l'argumentaire de marque dans la vidéo de présentation." },
    { n: 3,
      titre: "Cahier des charges du projet hôtelier",
      pages: "13-16",
      contenu: "Contexte et objectifs du projet, répartition des 100 chambres, espaces communs et services, contraintes techniques et architecturales, engagements RSE, budget (18-21 M€) et planning jusqu'à l'ouverture en N+3.",
      utile: "Fournit les contraintes chiffrées non négociables à respecter dans toute proposition — budget, capacité, délais, RSE." },
    { n: 4,
      titre: "Maquettes de l'hôtel",
      pages: "17-19",
      contenu: "Vues extérieures de la façade, hall d'accueil thématisé, chambre classique et chambre VIP.",
      utile: "Donne des repères visuels concrets pour décrire l'expérience et les différenciateurs perçus par le client." },
    { n: 5,
      titre: "Emplacement de l'hôtel dans le parc",
      pages: "20-21",
      contenu: "Position de l'hôtel entre les zones India, Kids Park et Jungle, accès depuis les entrées Lion et Mexico, et cartographie générale du parc.",
      utile: "Utile pour situer l'intégration de l'hôtel dans le parcours visiteur et pour l'accessibilité PMR." },
    { n: 6,
      titre: "Étude de marché des parcs d'attraction",
      pages: "22-24",
      contenu: "Contexte touristique belge, tendances des visiteurs (séjours courts, essor de l'hébergement), saisonnalité de la fréquentation, et profils chiffrés de quatre parcs concurrents.",
      utile: "Fournit les données de marché et de concurrence à citer dans la veille, le diagnostic et le positionnement." }
  ]
};
