var RESSOURCES = {
  "b1-Q1": {
    "intro": "<p>Cette question évalue la compétence C1.1 : construire une veille utile avant de savoir quoi en faire. Il faut nommer des objectifs qui délimitent un périmètre de recherche précis, puis choisir des outils et des sources dont on peut justifier la fiabilité — pas une liste générique de « veille internet ».</p>",
    "notions": [
      {
        "id": "six-veilles-c11",
        "nom": "Les six veilles de la compétence C1.1",
        "contenu": "<p>La compétence C1.1 ne demande pas « une veille », mais six veilles distinctes, chacune avec son propre objet : la veille marketing regarde les attentes et les comportements des clients ; la veille commerciale suit les prix, les canaux de vente et les pratiques des distributeurs ; la veille technologique repère les outils et innovations qui changent un métier ; la veille réglementaire surveille les lois et les normes applicables ; la veille sur les tendances comportementales observe l'évolution des usages et des attentes sociétales ; la veille RSE suit les pratiques durables et les labels du secteur.</p><p>Cette liste sert de grille de lecture : pour chaque sujet, on peut se demander laquelle des six veilles est mobilisée, et si une dimension a été oubliée. Un projet hôtelier, par exemple, croise vite plusieurs de ces veilles à la fois — la réglementation PMR est aussi une question RSE, le comportement des visiteurs relève à la fois du marketing et des tendances sociétales.</p><p>Le risque n'est pas de mal définir une veille isolément, mais de n'en traiter qu'une ou deux et de laisser croire que la veille se limite à « suivre la concurrence ».</p>"
      },
      {
        "id": "fiabilite-source",
        "nom": "Fiabilité d'une source",
        "contenu": "<p>Une source de veille n'est utile que si elle est fiable, et la fiabilité s'évalue avec quatre réflexes simples. Qui publie : un institut statistique officiel, une entreprise concurrente qui communique sur elle-même, ou un blog anonyme n'ont pas le même niveau de garantie. Avec quel intérêt : une source qui vend un produit ou défend une position a raison de biaiser son propos, ce qui ne la rend pas inutilisable mais impose de la recouper. À quelle date : une donnée de fréquentation touristique vieille de cinq ans ne dit rien d'un marché qui a changé de saisonnalité ou de concurrence entre-temps. Et surtout, l'information est-elle recoupée ailleurs : un chiffre isolé reste une hypothèse, le même chiffre confirmé par deux sources indépendantes devient un fait exploitable.</p><p>On distingue aussi les sources primaires — la donnée brute, collectée directement (une enquête, un rapport annuel, une statistique officielle) — des sources secondaires, qui commentent ou résument une source primaire (un article qui cite une étude). Une source primaire prime toujours sur une source secondaire quand les deux sont disponibles, parce que la secondaire ajoute une interprétation qui peut déformer le chiffre d'origine.</p><p>Citer « internet » ou « les réseaux sociaux » comme source ne répond à aucun de ces quatre critères : ce sont des canaux de diffusion, pas des garanties de fiabilité.</p>"
      }
    ],
    "modeles": [
      {
        "id": "veille-push-pull",
        "nom": "Veille push et veille pull",
        "contenu": "<p>Une veille se construit avec deux logiques complémentaires, pas une seule. En push, l'information vient à soi : alertes automatiques sur un mot-clé, newsletters professionnelles, flux d'actualité d'un secteur. L'avantage est le gain de temps une fois le dispositif réglé ; la limite est qu'on ne reçoit que ce qu'on a pensé à surveiller. En pull, on va chercher l'information activement : consulter le site d'un institut statistique, lire un rapport sectoriel, interroger une base de données professionnelle. Cette logique permet d'aller au-delà des sujets déjà identifiés, mais demande du temps dédié.</p><p>Pour appliquer ce modèle, la méthode est simple : lister d'abord ce qui peut être automatisé en push (les évolutions récurrentes à surveiller dans la durée), puis réserver le pull aux besoins ponctuels ou aux sujets qui demandent une recherche approfondie et non répétitive. Un dispositif de veille complet mobilise toujours les deux : le push évite de rater un signal, le pull permet de creuser un point une fois qu'il a été repéré.</p><p>L'erreur fréquente est de ne décrire que le pull (« je vais chercher sur… ») sans jamais organiser de veille récurrente automatisée, ce qui transforme la veille en recherche ponctuelle répétée plutôt qu'en surveillance continue.</p>"
      },
      {
        "id": "methodo-veille-5-etapes",
        "nom": "Méthodologie de veille en 5 étapes",
        "contenu": "<p>Répondre à une question de veille sans méthode produit une liste de sources sans logique. La méthode en cinq étapes donne cette logique : d'abord les objectifs — qu'est-ce que cette veille doit permettre de décider, et pour qui ; ensuite le périmètre — géographique, temporel, et le choix des veilles concernées ; puis les sources et outils — nommés précisément, pas génériques ; ensuite la collecte et l'analyse — trier ce qui est pertinent de ce qui ne l'est pas, recouper ; enfin la diffusion — sous quelle forme et à quelle fréquence l'information remonte à ceux qui en ont besoin.</p><p>Appliquée pas à pas, cette méthode évite l'écueil le plus fréquent : présenter des outils avant d'avoir formulé un objectif. Un outil n'a de sens que relié à une décision qu'il permet d'éclairer — un agrégateur de contenu sert à quelque chose seulement si l'on sait d'abord ce qu'on veut y trouver et pourquoi.</p><p>Pour une question d'examen, les deux premières étapes (objectifs, périmètre) et la troisième (sources et outils) répondent directement aux critères d'évaluation ; les deux dernières (collecte/analyse, diffusion) servent surtout à montrer que la veille s'inscrit dans un processus et pas dans une recherche isolée.</p>"
      }
    ],
    "application": "<p>L'énoncé demande deux choses distinctes : des objectifs de veille pour le lancement de l'hôtel, et des outils/sources précis. Utiliser la grille des six veilles pour vérifier qu'aucune n'est oubliée : un hôtel thématique dans un parc mobilise au minimum la veille marketing (attentes des familles pour un séjour combiné hôtel + parc), la veille commerciale (politiques tarifaires des hôtels de parcs concurrents, poids des plateformes de réservation), la veille réglementaire (classement hôtelier en Région flamande, normes PMR déjà citées à hauteur de 8 chambres minimum, Code du tourisme), la veille RSE (labels environnementaux de l'hébergement, cohérence avec le groupe Compagnie des Alpes) et la veille sur les tendances comportementales (essor des séjours courts, croissance du marché des parcs de +7,4 % par an selon l'annexe 6).</p><p>Pour chaque veille retenue, nommer un objectif précis (pas « suivre la concurrence » mais « comparer les grilles tarifaires des hôtels adossés à Pairi Daiza et Plopsaland ») et des outils crédibles au sens des quatre critères de fiabilité — l'énoncé suggère déjà des pistes (rencontres professionnelles, magazines spécialisés, instituts d'enquêtes, IA et agrégateurs de contenu) qu'il faut rendre concrètes plutôt que les recopier telles quelles.</p>",
    "sources": [
      "Développer une posture stratégique de veille — méthodologie de veille, push/pull et étapes du processus",
      "Explorer les champs de veille pour éclairer les décisions — fiabilité des sources et typologie des tendances"
    ]
  },
  "b1-Q7": {
    "intro": "<p>Cette question évalue la compétence C1.3 sur deux plans à la fois : des différenciateurs dont l'avantage se mesure face à la concurrence, et une expérience pensée pour des publics différents, pas pour un visiteur-type imaginaire. Les deux exigences se répondent : un différenciateur qui n'est accessible qu'à une partie des visiteurs perd une partie de sa valeur.</p>",
    "notions": [
      {
        "id": "differenciateur-valeur-mesurable",
        "nom": "Différenciateur et valeur ajoutée mesurable",
        "contenu": "<p>Un différenciateur n'est pas simplement ce qui rend une offre différente : n'importe quel détail rend une offre différente. Un différenciateur est un écart qui compte pour le client et qu'un concurrent ne propose pas, ou propose moins bien. Le critère central est la mesurabilité : « offre une expérience unique » ne se vérifie pas ; « seul hôtel de parc adossé à un parc animalier de plus de 100 espèces » se vérifie, parce qu'on peut le comparer point par point à ce que proposent les concurrents identifiés.</p><p>Pour construire un différenciateur mesurable, il faut donc toujours l'énoncer en miroir d'un concurrent nommé : ce que l'offre propose, ce que les concurrents ne proposent pas ou proposent différemment, et en quoi cet écart pèse réellement dans la décision d'un client (durée de séjour, fréquence de visite, panier moyen). Un avantage réel mais qui n'intéresse pas la cible visée n'est pas un différenciateur utile pour cette question.</p><p>Le piège classique est de lister des qualités (propreté, accueil, décor) qui sont attendues par tous les clients de toute façon, et qui ne distinguent donc rien : un différenciateur se prouve par contraste, pas par description.</p>"
      },
      {
        "id": "inclusion-accessibilite",
        "nom": "Inclusion et accessibilité",
        "contenu": "<p>Les deux mots se recoupent mais ne désignent pas la même chose. L'inclusion porte sur la représentation : est-ce que la diversité réelle des visiteurs (âges, configurations familiales, origines, situations de handicap visible ou invisible, budgets) est prise en compte dans la conception de l'offre, et pas seulement mentionnée après coup. L'accessibilité porte sur l'usage effectif : une famille avec une personne à mobilité réduite peut-elle réellement circuler, réserver, profiter des équipements — au-delà de la simple conformité réglementaire.</p><p>Sur le plan réglementaire, une norme comme l'EN 301549 (déjà citée pour les chambres PMR) fixe un plancher obligatoire ; l'inclusion va au-delà en pensant aussi les handicaps invisibles, les familles nombreuses, les budgets contraints, ou les visiteurs qui découvrent le site pour la première fois et ont besoin de repères clairs. Une expérience inclusive se construit sur plusieurs dimensions : l'accès physique, mais aussi l'information (signalétique claire, plusieurs langues), le prix (offres adaptées à différents budgets) et l'accueil (personnel formé à des situations variées).</p><p>Le piège est de traiter l'inclusion comme un paragraphe à part, uniquement centré sur le handicap physique, alors que le critère demande une expérience pensée pour la diversité des publics dans son ensemble.</p>"
      },
      {
        "id": "moments-de-verite",
        "nom": "Moments de vérité",
        "contenu": "<p>Un moment de vérité est un point de contact où la perception du client bascule, en bien ou en mal, plus que les autres. Ce ne sont pas tous les points de contact qui pèsent autant : l'arrivée à l'accueil d'un hôtel thématique, le moment où une famille avec un enfant en fauteuil découvre si l'espace est réellement praticable, ou le premier contact avec le personnel comptent davantage que, par exemple, la couleur d'un couloir.</p><p>Pour une question sur l'inclusion, les moments de vérité aident à prioriser : plutôt que de décrire l'inclusion partout de façon diffuse, on peut identifier deux ou trois moments où son absence serait la plus pénalisante (l'arrivée, la réservation, l'accès aux chambres et aux espaces communs) et concentrer les propositions concrètes sur ces moments-là.</p><p>Le repère pratique est de se demander, pour chaque étape du séjour, ce qui se passe si ce moment échoue pour un visiteur en particulier — une famille nombreuse, une personne à mobilité réduite, un visiteur non francophone — et de vérifier que l'offre y répond spécifiquement, pas seulement en moyenne.</p>"
      }
    ],
    "modeles": [
      {
        "id": "pine-gilmore",
        "nom": "Modèle de Pine & Gilmore",
        "contenu": "<p>Pine et Gilmore décomposent une expérience réussie en quatre dimensions, organisées sur deux axes : la participation du client (passive ou active) et le lien avec l'environnement (absorption ou immersion). Le divertissement est une participation passive dans un environnement qu'on absorbe (regarder un spectacle) ; l'apprentissage est une participation active dans un environnement qu'on absorbe (comprendre quelque chose de nouveau) ; l'évasion est une participation active dans un environnement où l'on est immergé (se sentir transporté dans un autre univers) ; l'esthétique est une participation passive dans un environnement immersif (être entouré d'un décor marquant sans agir dessus).</p><p>La méthode d'application est simple : pour un hôtel thématique, vérifier que chacune des quatre dimensions est activée par au moins un élément concret — le décor et l'histoire de la mascotte pour l'esthétique et l'évasion, des activités liées au parc animalier pour l'apprentissage, des animations pour le divertissement. Un projet qui n'active qu'une seule dimension (en général l'esthétique, via la décoration) laisse l'expérience incomplète alors que le modèle en prévoit quatre.</p><p>Ce modèle sert aussi à vérifier l'inclusion : chaque dimension doit rester accessible à des publics différents, pas seulement pensée pour un visiteur standard.</p>"
      }
    ],
    "application": "<p>L'énoncé demande de mettre en avant des différenciateurs de l'hôtel « Le Royaume de Léo » et d'expliquer leur effet sur l'attractivité et l'inclusion. Les données mobilisables sont dans l'annexe 6 (les quatre concurrents chiffrés — parc animalier et botanique, licences de dessins animés, sensations fortes, offre généraliste — avec leur fréquentation respective) et dans l'annexe 3 (le cahier des charges de l'hôtel : 100 chambres dont 8 PMR minimum aux normes EN 301549, hall thématisé, espaces familiaux). Comparer chaque caractéristique du projet à ce que ces concurrents proposent ou ne proposent pas permet de faire émerger des différenciateurs mesurables, plutôt que des qualités génériques.</p><p>Pour le volet inclusion, s'appuyer sur les moments de vérité du séjour hôtelier (arrivée, accès aux chambres, restauration, espaces communs) pour vérifier concrètement, à chaque étape, si les 8 chambres PMR et les équipements prévus par le cahier des charges suffisent à couvrir la diversité des publics visés (familles nombreuses, visiteurs transfrontaliers non francophones, budgets contraints), ou s'il faut proposer des ajouts.</p>",
    "sources": [
      "Créer un contenu de marque différenciant et ciblé — modèle de Pine & Gilmore, distinction CX/UX et moments de vérité",
      "Construire les bases d'une stratégie marketing globale et digitale — positionnement et USP",
      "Poser les bases d'une stratégie marketing orientée innovation — design universel et prise en compte de la diversité des usages"
    ]
  }
};
